name: face_swap
channels:
  - defaults
dependencies:
  - python=3.6.9
  - pip=19.1.1
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - pillow=7.2.0
  - tqdm=4.32.1
  - tblib=1.6.0
  - pip:
      - numpy==1.16.4
      - opencv-python==4.1.*
      - dacite==1.0.2
      - dataclasses
      - boto3
      - requests==2.21.0
      - matplotlib==3.1.0
#      - PyYAML==5.3
      - torch==1.4.0
      - torchvision==0.5.0
      - tensorboard==1.14
      - opencv-python-headless==4.1.*
      - visdom==0.1.8.9
      - facenet_pytorch==2.3.0
      - tensorflow==1.14  # we don't use it but tensorboard has issues without it
      - streamlit==0.64.0
