name: reface
channels:
  - defaults
dependencies:
  - python=3.7.3
  - pip=19.1.1
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - pillow=6.0.0
  - tqdm=4.32.1
  - tblib=1.6.0
  - pip:
      - numpy==1.16.4
      - pyudev==0.21.0
      - opencv-python==4.2.0.32
      - dacite==1.0.2
      - fire==0.1.3
      - requests==2.21.0
      - absl-py==0.7.0
      - s3transfer==0.2.0
      - tblib==1.4.0
      - matplotlib==3.1.0
#      - PyYAML==5.3
      - tifffile==2019.7.26.2
      - torch==1.4.0
      - torchvision==0.5.0
